# Generated by Django 5.0.6 on 2024-07-16 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veranum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='numero_habitacion',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo_habitacion',
            field=models.CharField(choices=[('simple', 'Simple'), ('doble', 'Doble'), ('suite', 'Suite')], max_length=50, verbose_name='Categoría'),
        ),
    ]
