# Generated by Django 5.0.6 on 2024-07-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veranum', '0002_habitacion_numero_habitacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='precio_por_dia',
        ),
        migrations.AddField(
            model_name='habitacion',
            name='servicios_extras',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
