# Generated by Django 5.0.6 on 2024-07-16 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veranum', '0003_remove_habitacion_precio_por_dia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='servicios_extras',
        ),
    ]
