# Generated by Django 5.0.6 on 2024-07-16 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veranum', '0004_remove_habitacion_servicios_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='precio_por_dia',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habitacion',
            name='servicios_extras',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
