# Generated by Django 5.0.6 on 2024-07-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veranum', '0005_habitacion_precio_por_dia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='historial_precios',
            field=models.TextField(blank=True),
        ),
    ]
